### ISSUE TITLE
kube2iam loses pod's credentials?

### ISSUE THREAD

**Issue by erkolson** [jtblin/kube2iam#102]
I occasionally see pods lose their ability to get AWS credentials, perhaps after an expiration.  From a pod in this state, I see this when querying the metadata service:
```
$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
Unable to find role for IP 10.33.92.3
```
This is on a pod that has been running for days or weeks with no problems using AWS credentials.

The logs for the `kube2iam` pod on same node as the above pod show what I assume is a corresponding event: 
```
[kube2iam-2sqd9] time="2017-09-27T18:08:57Z" level=info msg="GET /latest/meta-data/iam/security-credentials/ (404) took 3107885116 ns" req.method=GET req.path="/latest/meta-data/iam/security-credentials/" req.remote=10.33.92.3 res.duration=3107885116 res.status=404
```

**Comment by jrnt30** [comment]
What version of Kube2IAM are you running?

**Comment by erkolson** [comment]
`0.6.5`

**Comment by jrnt30** [comment]
Do you have the CronJob api enabled and running in your cluster? #92 addressed a caching issue with that

**Comment by erkolson** [comment]
I do have the CronJob api enabled.  I don't see any reference to cronjobs in that issue discussion or the code delta.

**Comment by jrnt30** [comment]
#95 has more details that link back. It was a subtle state transition that the old store didn’t manage

**Comment by erkolson** [comment]
Ok, cool, I'll look at that too.  Are they in a release yet.

**Comment by jtblin** [comment]
Yes it was released in 0.8.x. Feel free to re-open if you see the issue happening again.

**Comment by WxFang** [comment]
Still seeing it in 0.10.0.

**Comment by renperez** [comment]
we are experiencing the same issue. "GET /latest/meta-data/iam/security-credentials (404) took 2533266016.000000 ns" 
any update? we are using the latest kube2iam

**Comment by colegatron** [comment]
same problem @renperez here.
it is happening too often

**Comment by eug-maly** [comment]
the same issue happens from time to time (v0.10.11). Is it possible to add repsonse_code!=200 to metrics? oh how we can monitor this behavior?
