### ISSUE TITLE
Govcloud support

### ISSUE THREAD

**Issue by robertglen** [jtblin/kube2iam#103]
It appears the implementation of the AWS STS interface does not specify a region to connect to, so it uses default (us-east-1?).

This means AssumeRole functionality will work everywhere **EXCEPT** Govcloud.  This sucks given security is the whole reason Govcloud (and presumably this project) exists.

Perhaps the region endpoint for the STS interface can be overridden at command line?  Or have the default region be _smart_ and leverage the auto discovered ARN base trigger a change to the default region you connect to.

ALL govcloud IAM ARNs will begin with:   arn:aws-us-gov:iam:

So if 'aws-us-gov' is in the ARN, then maybe automatically use the 'us-gov-west-1' region name for the STS session?

**Comment by jtblin** [comment]
You can set the AWS region via the standard AWS_REGION environment variable.

**Comment by robertglen** [comment]
Excellent.  I'll give it a shot.

**Comment by robertglen** [comment]
Closing the loop on this.  The region specification via env var worked.  Good nugget of info for anyone else using this in Amazon's only govcloud region :)
