### ISSUE TITLE
Is 0.8.2 the latest release?

### ISSUE THREAD

**Issue by gtaylor** [jtblin/kube2iam#107]
I was just looking at the releases page, and 0.8.2 is sitting in a weird not-latest-release state without release notes. Is 0.8.2 the suggested version right now, or should I stick to 0.8.1?

**Comment by erkolson** [comment]
Looks like the only difference is the last commit, which is documentation only:
https://github.com/jtblin/kube2iam/commit/954a5fbf14e7c3acdac440956c894b815f8dd36a

**Comment by jtblin** [comment]
It was only stripping vendors from the binary, no functional changes. Now the last one is [0.9.0](https://github.com/jtblin/kube2iam/releases/tag/0.9.0)
