### ISSUE TITLE
IPtables rule not working

### ISSUE THREAD

**Issue by johnwchadwick** [jtblin/kube2iam#11]
I am not 100% sure why, but the iptables rule is not working for our Kubernetes setup.

I've found that if I do not specify the interface as docker0 and instead specify the source as my private subnet (in my case, 100.64.0.0/10) it works perfectly. Unfortunately, for some completely unobvious reason, trying to specify a CIDR range as the source doesn't work in code (I tried it in my fork.) Maybe has to do with incompatibilities of iptables on the host and the container? It works if I run the iptables rule directly on the host.

It is worth noting that I'm using the VPC networking and not an overlay network.

**Comment by jtblin** [comment]
OOC are you setting up the rule manually or letting kube2iam to set it?

**Comment by johnwchadwick** [comment]
I am trying to make the automatic IPtables setup work. When doing it manually, though, I can make it work when making the aforementioned modifications.

**Comment by jtblin** [comment]
Looking at [coreos go-iptables tests](https://github.com/coreos/go-iptables/blob/master/iptables/iptables_test.go), CIDR should work as source. Going to close this issue as it has been opened for a while as there has been no other report and there is no repro step. Please feel free to re-open if you think it is a valid issue.
