### ISSUE TITLE
is host ip required when setting `--iptables=true`?

### ISSUE THREAD

**Issue by rickypai** [jtblin/kube2iam#12]
just wondering, since kube2iam already runs on the host network, it could just acquire the local IP through `hostname -i` or even `169.254.169.254/latest/meta-data/local-ipv4`. confirmed both by running inside a `kube2iam` pod. not sure if it's specific to my networking setup.

**Comment by jtblin** [comment]
Good point. We could probably just use [os.Hostname](https://golang.org/pkg/os/#Hostname).

**Comment by Just-en-Time** [comment]
Just to follow up on this--in attempting to dynamically set the HOST_IP, I've tried setting the arg `- "--host-ip=$(/bin/hostname -i)"`, but without success. Do you have advice or suggestions that have worked for you?

**Comment by jtblin** [comment]
Can use ec2 metadata API e.g. `curl 169.254.169.254/latest/meta-data/local-ipv4`

**Comment by jtblin** [comment]
`os.Hostname` is probably not going to work, setting up the ip via `curl -s 169.254.169.254/latest/meta-data/local-ipv4` seems easy enough so closing as Won't fix.
