### ISSUE TITLE
For kube-router users: interface is kube-bridge

### ISSUE THREAD

**Issue by HagaiBarel** [jtblin/kube2iam#120]
Just putting this here, you might want to add this to the readme, if you're using [kube-router](https://github.com/cloudnativelabs/kube-router) as the CNI, the default interface is `kube-bridge`.

Tested with `kube-router` on `CoreOS` container linux

**Comment by jrnt30** [comment]
Thanks for the feedback.  A quick PR would be most welcome!

**Comment by HagaiBarel** [comment]
Done, see #123

**Comment by jtblin** [comment]
Merged, thanks!
