### ISSUE TITLE
For calico networking users: interface is cali+

### ISSUE THREAD

**Issue by TaiSHiNet** [jtblin/kube2iam#14]
If you're using calico as a network manager (instead of flannel), interface names are cali1234567890, we can leverage iptables wildcard (+). More info:
https://www.centos.org/docs/5/html/5.1/Deployment_Guide/s2-iptables-options-parameters.html

**Comment by jtblin** [comment]
You can specify the host interface via the `--host-interface` flag, is there anything that needs to be done in addition to that or shall we just update the README about it?

**Comment by TaiSHiNet** [comment]
Just assigning `--host-interface=cali+` works like a dream, it took a bit to figure out so if you want to point it out in the README that would be great.

**Comment by jtblin** [comment]
Awesome, thanks for the follow-up @TaiSHiNet 👍 
I will update the docs accordingly.
