### ISSUE TITLE
Support for amazon-vpc-routed-eni 

### ISSUE THREAD

**Issue by cdelpinogeo** [jtblin/kube2iam#144]
Hi there,

We just deployed a Kops deployed kubernetes cluster onto aws onto a private subnet. We deployed kube2iam and saw the following error:
```
route ip+net: no such network interface
```
Noticed that we are using `amazon-vpc-routed-eni` as our networking option. Does kube2iam support this?

**Comment by jrnt30** [comment]
I have not tried this but you could look at using https://github.com/jtblin/kube2iam#iptables arguments to customize this to the appropriate interface name.

**Comment by cdelpinogeo** [comment]
We figured it out. The interface used is `docker0`. Thanks!
