### ISSUE TITLE
EKS iam role error after updating a deployment image

### ISSUE THREAD

**Issue by josepplaltg** [jtblin/kube2iam#150]
We're getting this  error on a pod after updating the deployment
`E0621 15:45:50.925889       1 aws_manager.go:121] Failed to regenerate ASG cache: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F0621 15:45:50.925922       1 cloud_provider_builder.go:137] Failed to create AWS Manager: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
`
The pod is a cluster-autoscaler that has been running fine until we updated the image and a new pod started, seems there's some kind of issue with the new pod trying to get the credentials from kube2iam.

**Comment by jrnt30** [comment]
- What version of Kube2IAM and K8 are you running? 
- Were the logs for Kube2iam useful here?  
- Are you consistently seeing this issue or was it a one-off?

**Comment by josepplaltg** [comment]
Hi  @jrnt30 , finally was a communication error, some nodes wasn't able to communicate with others, sorry for that, after some SG fixing now's working fine.
