### ISSUE TITLE
annotate multiple roles to be assumed

### ISSUE THREAD

**Issue by raoofm** [jtblin/kube2iam#153]
Is there a way to 
Add an iam.amazonaws.com/role annotation to the pods with multiple roles that you want to assume for this pod.

**Comment by jrnt30** [comment]
There is not supported by Kube2IAM and this functionality is generally not something that I've seen used generally in the AWS ecosystem. I generally think of Kube2IAM very analogous to an EC2 IAM role, we are providing permissions to a given workload where Ec2 IAM roles are also 1 - 1 mapping with a given instance. 

A few potential solutions would be to: 

- Create a "Consolidating" role that has the policies from all of the roles you want it to use. (This would be the most straightforward and natural approach in my opinion). 

- Retain your existing roles that are present and create a net-new IAM role that is allowed to assume the existing roles.  In your application code you could create multiple sessions to AWS to assume those roles directly, however this would require managing multiple connections to AWS split out by what the different policies allow which would be fairly undesirable.

**Comment by lgg42** [comment]
Can't wait for this to hit master! great work! thankssss

**Comment by lgg42** [comment]
> Just added this capability in #229 . It was super simple due to the clean codebase and good test coverage. Great codebase @jrnt30 and @jtblin !

Can't wait for this to hit master! great work! thankssss
