### ISSUE TITLE
Need help in figuring out why kube2iam is not running

### ISSUE THREAD

**Issue by vchan2002** [jtblin/kube2iam#163]
So, I've been troubleshooting this all day, and I have seen that.

a.  The role assumption works 
b.  The role assumption has sufficient rights as I did the assumption myself and was able to do the tasks that the assumed role does.
c.  The IP tables are setup correctly with ENI+, routing requests from the metadata to kube2iam as I am using EKS
b.  enabling both --verbose and --debug, and testing curl to /debug/store.  When curling debug/store, it shows, on "rolesbyIP", the role that it is trying to assume.
e.  kube2iam version is 0.10.2.
f.  Looking at kube2iam logs, it appears that it is trying to assume the role.  There are no additional messages after that.

time="2018-08-28T01:46:53Z" level=debug msg="Pod OnUpdate" pod.iam.role="{ROLE NAME}" pod.name=aws-cli pod.namespace=kube-system pod.status.ip=10.0.54.93 pod.status.phase=Running

f.  In the end, when testing this setup (I am using the aws-cli example in the dockerhub page), the only thing that shows up is....

An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

I'm running out of ideas on how to proceed next....

**Comment by jrnt30** [comment]
Is this happening for all containers or just this one? With the debug logs, you should also see the calls to the API endpoint for the pod and the response codes.  Including those would be helpful to diagnose the issue.  

But if you look, are the requests for the credentials occurring before or after that `OnUpdate` statement that includes the `Running` pod?  There are some cases where the Pod will attempt to access the CLI prior to Kube2IAM seeing the pod "come through" with an IP properly.  

A few other things to try would be: 
- Adding in a healthy sleep for the container's entrypoint and manually ensuring your permissions for the role are correct (messed that up myself before) 
- Assuming that works, adding in a sleep prior to the application start to test the race condition use case.

**Comment by vchan2002** [comment]
So..... I have been checking the logs, and I also have made the aws-cli container run with a tty so that I can exec into it and run whatever aws-cli commands I wish.  So, here's what I've seen.

When the container starts up, I see that that kube2iam is seeing the pod starting up requesting the IAM role....

2018-08-28T16:21:50.683043492Z time="2018-08-28T16:21:50Z" level=debug msg="Pod OnUpdate" pod.iam.role="{role it is trying to assume}" pod.name=aws-cli pod.namespace=kube-system pod.status.ip=10.0.54.127 pod.status.phase=Running

However, when I kubectl exec bash into the container into the container and try to start running aws commands and getting access denied, kube2iam does not log anything.

I also tried to do a get of http://169.254.169.254/latest/meta-data/iam/security-credentials/, per the instructions below, and I only get the IAM role of the EKS node, not the IAM role that it has the rights to assume.

https://labs.bench.co/blog/2018/6/4/kube2iam-secure-kubernetes-services-on-aws

I know that the pod shouldn't be in kube-system namespace, but it really shouldn't matter when it comes down to, right?

**Comment by vchan2002** [comment]
Okay..... turns out it's my noob-ness on my end... although it's running on EKS, it actually is using calico networking, so the setting on kube2iam is cali+, not eni+.  Tweaked the daemonset, restarted it, and it works beautifully.

**Comment by jrnt30** [comment]
Glad to hear it!

**Comment by dhiman-halder** [comment]
@vchan2002 - Are you saying for a setup on EKS that uses Calico networking, we should use cali+ instead of eni+ in kube2iam ?

**Comment by zghafari** [comment]
You should use cali+
