### ISSUE TITLE
Kube2iam requires user account to be trusted rather than instance role

### ISSUE THREAD

**Issue by carpenterm** [jtblin/kube2iam#169]
Hi there,

I'm trying to get kube2iam working in our environment, Kubernetes is deployed using kops.

I've setup the additional policies and trust relationships as per the docs to allow the node instance role to assume the target role, and when I ssh to the k8s nodes I can successfully assume the target role using the instance role. E.g.

`aws sts assume-role --role-arn arn:aws:iam::123456789012:role/s3-access-role --role-session-name mysession --duration-seconds 3600`

This gives me creds and a token and I can use those to access s3 buckets.

When I add this same ARN to a pod, exec to the pod and try the same thing I receive an error that there are no credentials. When I run curl to the metadata API I get an error:

` # curl http://169.254.169.254/latest/meta-data/iam/security-credentials/s3-access-role
AccessDenied: User: arn:aws:iam::111111111111111:user/cross-account-user is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789012:role/s3-access-role
	status code: 403, request id: 2492776c-b699-11e8-ac31-1f22838ee34f`

The cross-account-user is our CI user, which has permissions to assume roles in dev, staging and production accounts and is the user that was used to deploy the cluster. If I add this cross-account-user ARN as a trusted principle in the s3-access-role then I can successfully retrieve credentials via kube2iam but this isn't desirable since the cross-account-user has access to all environments.

From what I can tell kube2iam should be trying to use the node role to assume the credentials of the target role, not the underlying user account.

Any ideas on where I could be going wrong?

Thanks,
Matt

**Comment by jrnt30** [comment]
That's an interesting one!  I'm fairly perplexed as I haven't see that type of behavior before. 

Just curious: 

- What does `aws sts get-caller-identity` show in and out of the pod?  
- What happens if you remove the `s3-access-role ` from your curl? 
- Is the pod being launched normally or is it launched in some other way (Jenkins Kuberentes plugin or something like that)?

**Comment by carpenterm** [comment]
Yeah, it really doesn't make sense!

Running `aws sts get-caller-identity` on the node works as expected:
```root@ip-10-XX-XXX-216:/home/ubuntu# aws sts get-caller-identity
{
    "Account": "123456789012", 
    "UserId": "AROAJ***********VXW:i-065**********da6d", 
    "Arn": "arn:aws:sts:: 123456789012:assumed-role/nodes.cluster-name.k8s.local/i-065********da6d"
}
```

If I add any role to the pod annotation, other than the admin role that our CI user assumes to provision the cluster using kops, then when I run `aws sts get-caller-identity` inside the pods I get:
```bash-4.3# aws sts get-caller-identity
Unable to locate credentials. You can configure credentials by running "aws configure".
```
I assume this is because it is getting a 403 stating that the cross-account-user is not authorized.

If I annotate a pod with the admin role it works as expected, `aws sts get-caller-identity` works inside the pod and gives me the admin role details.

I can assume the s3-access-role no problem on the node. I also confirmed that if I remove the nodes IAM role from the trust relationship I can no longer assume the s3-access-role, so that is working as expected. 

If I remove the s3-access-role from the curl command it prints `s3-access-role`

The pod is being launched using kubectl:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: role-test
  labels:
    name: role-test
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::123456789012:role/s3-access-role
spec:
  containers:
  - image: uzokis/fancy-docker-awscli-curl
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 9999999"
    name: aws-cli
EOF
```

We are using the Amazon CNI and the latest stable Helm chart to deploy kube2iam.

We do have our IAM roles managed by another team - so they provide the CI user and ability to assume an admin role for each environment. We are then able to create and manage roles ourselves and assume any roles within our own account. 

Given that everything works as expected on the node using the CLI it is difficult to see how that could be the issue.

Any suggestions gratefully received!

**Comment by carpenterm** [comment]
Just wanted to add that I believe that the reason that everything works when we annotate the pod with the admin role is that the admin role has the cross-account-user in it's trust relationship. Which seems to confirm that kube2iam is trying to assume the annotated roles using the credentials of the underlying user vs the node role.

Is there any way to tell which credentials kube2iam has assumed?

**Comment by jrnt30** [comment]
Kube2IAM will use the default provider credential toolchain.  It will first look for an explicit credentials file, move onto the standard environment variables and finally attempt to call the metadata service for it's credentials if it hasn't gotten any yet. 

To be honest I am having a hard time to wrap my head around how the symptoms you are expressing could happen so this isn't super well structured debugging, but in the Kube2IAM pod itself you could try: 

- `curl http://169.254.169.254/latest/meta-data/iam/info`
- `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/`

A few other things that would be useful:
- Validate that you have the correct interface bound for the CNI plugin you are using
- Enable the verbose logging on Kube2IAM and validate the requests and response you are observing in the annotated pod match up 
- Enable the debug endpoint of Kube2IAM and dump the internal information of what Kube2IAM is storing

**Comment by carpenterm** [comment]
Ahhhhh, your comment about using the default credential provider pointed me in the right direction! 

The person who deployed it saw the `aws.secret_key` and `aws.access_key` params in the helm chart values.yaml https://github.com/helm/charts/blob/master/stable/kube2iam/values.yaml and automatically filled them in with our CI user! 

As soon as I removed them everything started working as expected. Thanks so much for your help folks!
