### ISSUE TITLE
--iptables option: race condition?

### ISSUE THREAD

**Issue by devkid** [jtblin/kube2iam#170]
I'm currently setting up kube2iam in our cluster and just thought about that. If you let kube2iam set up the iptables rule, is there not a security risk by means of a race condition? If you manage to start a pod on an new instance before kube2iam is started on this node, you can basically assume the instance role.

Is this correct or am I missing something here? If this is correct, this should be documented with a large warning that this can happen and if you don't trust the pods that get deployed to the cluster you should prefer to set up this iptables rule *before* starting the kubelet.

**Comment by jrnt30** [comment]
You are not incorrect, if the IP Tables aren't updated then the normal IAM Metadata service rules apply on the host.  Please feel free to create a PR with updated verbiage that you think calls this out more appropriately.
