### ISSUE TITLE
EKS with Calico Network Plugin

### ISSUE THREAD

**Issue by dhiman-halder** [jtblin/kube2iam#180]
When we are installing the Calico Network Plugin Engine on EKS and using "cali+" for "host-interface", Kube2Iam stops working for us. It is no longer able to resolve the IAM role specified through annotation and always falls back to the worker node IAM role.

`apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2iam
  namespace: kube-system
---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: kube2iam
    rules:
      - apiGroups: ['']
        resources: ['namespaces','pods']
        verbs: ['get','watch','list']
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kube2iam
    subjects:
    - kind: ServiceAccount
      name: kube2iam
      namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: kube2iam
      apiGroup: rbac.authorization.k8s.io
kind: List
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    app: kube2iam
spec:
  selector:
    matchLabels:
      name: kube2iam
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      serviceAccountName: kube2iam
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          imagePullPolicy: Always
          name: kube2iam
          args:
            - '--auto-discover-base-arn'
            - '--auto-discover-default-role=true'
            - '--iptables=true'
            - '--host-ip=REPLACE_HOST_IP'
            - '--node=REPLACE_NODE_NAME'
            - '--host-interface=cali+'
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true`

**Comment by whereisaaron** [comment]
EKS with the recommended Calico configuration uses 'eni' and not 'cali' as the interface prefix
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.3/calico.yaml
```
  # Use eni not cali for interface prefix
  - name: FELIX_INTERFACEPREFIX
     value: "eni"
```
