### ISSUE TITLE
Nodes are not assuming any roles

### ISSUE THREAD

**Issue by jaygorrell** [jtblin/kube2iam#19]
Let me first just say that I assume this is something I'm doing wrong since others don't seem to have an issue.

With that said, I'm running a vanilla kops-created kubenet cluster. I've attached an extra role to my masters and nodes both that allow them to assume any role, as well as created a new role with the access I want (DynamoDB) and granted the master/node roles as trusted.

I know the IAM side of things is set up properly since I can ssh into one of my cluster nodes and run `aws sts` to get credentials for the dynamo role (but not other roles). However, when running the exact example, with iptables=true and `s3 ls` changed to `dynamodb list-tables`, my pod appears to just not assume a role at all. The error reported from the pod is this:

`An error occurred (AccessDeniedException) when calling the ListTables operation: User: arn:aws:sts::<redacted>:assumed-role/nodes.k8s.dev.redacted/i-068a7d585ad916589 is not authorized to perform: dynamodb:ListTables on resource: *`

I even tried an IAM policy that grants everything except DDB access to the nodes but it had no impact. My guess is there's something I missed (perhaps specific to kops) needed to get kube2iam functioning? The logs only show me startup information about listening on 8181 without any updates as I create new pods.

**Comment by mgoodness** [comment]
What kind of networking are you using? I know when I switched from flanneld to CNI, I had to specify `--host-interface=cni0` in the container's args instead of relying on the default `docker0`. Of course, that's assuming you're using the `--iptables` and `--host-ip` options as well.

**Comment by jaygorrell** [comment]
Hmm, that might be on the right path. I'm using `kubenet`, which is the default for kops.

**Comment by jaygorrell** [comment]
Got it! Thanks for the pointer @mgoodness.

If anyone comes here trying to get kube2iam working with kops (on kubenet), the answer is `--host-interface=cbr0`.
