### ISSUE TITLE
More restrictive permissions?

### ISSUE THREAD

**Issue by mgoodness** [jtblin/kube2iam#2]
@jtblin mentioned in https://github.com/kubernetes/kubernetes/issues/23580#issuecomment-230654583 that the README needs an update. I'm looking to deploy kube2iam to my clusters soon, so this would be a great time to share any refinements.

 Thanks!

**Comment by jtblin** [comment]
@mgoodness I'll update the readme, but basically just replace `root` in the Trust Relationship by the name of the role for the node that kubernetes worker is deployed on e.g.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::123456789012:role/platform-dev-kubernetes-common-NodeIAMRole-7WEHDM7P3F5C"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Comment by jtblin** [comment]
Updated README as well.
