### ISSUE TITLE
Using kube2iam on a bare metal cluster outside of AWS

### ISSUE THREAD

**Issue by michas2** [jtblin/kube2iam#201]
Is it possible to use kube2iam outside of AWS, i.e. in an environment that does *not* already provide a metadata server?

I expected simply setting access_key/secret_key would be enough for kube2iam to provide a proper metadata service for my cluster.

It works fine only for a short while until kube2iam notices the absence of any upstream metadata server and simply gives up. :(

It seems like the only option is to set `--metadata-addr=mock:9090` to some kind of mock, but that really feels unneeded and in a first try was unsuccessful. (`iptables v1.6.1: host/network 'mock:9090' not found`)

Did I miss anything? Is there any good reason why we actually need some upstream server? (After all I only want my role.)

**Comment by SharpEdgeMarshall** [comment]
If I understand correctly you would like to use some user credentials, instead of the role assigned to the EC2 instance, to assume the role requested, is that correct? 
It's an interesting feature to add that would allow the use of AWS roles also without EC2 instances.

**Comment by michas2** [comment]
Yes, that's exactly the idea.
I now switched to kiam, which works fine. :)

**Comment by luckielordie** [comment]
Is there a status on this feature? I'm currently finding myself with the same use case.
Thanks :)
