### ISSUE TITLE
Ability to return EC2 instance credentials from within k8s pod

### ISSUE THREAD

**Issue by mklumpp1** [jtblin/kube2iam#202]
We are running with the default config as shown below on image version: 0.10.6

- args:
        - --app-port=8181
        - --base-role-arn=arn:aws:iam:...
        - --iptables=true
        - --host-interface=lxc+
        - --host-ip=$(HOST_IP)

This will create the IP table rules on the host, such as: 
DNAT       tcp  --  anywhere             169.254.169.254      tcp dpt:http to:x.y.z.d:8181 

However we are able to access the EC2 host credentials from within the pod, such as :  curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance

which will then return the EC2 instance credential, which is quite concerning.

I'm assuming we are configuring something wrong?

Thanks for your help

**Comment by SharpEdgeMarshall** [comment]
From my understanding, the credentials that you get using that call are only used internally by AWS to identify the instance.
Maybe I'm wrong but I tried to do some calls using these credentials but it looks like that they don't have any permission granted.

**Comment by mwhittington21** [comment]
Just did my own testing on this as well, after finding the issue independently. It seems like these credentials cannot be used for anything that the node role can do, so this isn't a problem.

If there is evidence to the contrary I will gladly reopen this ticket.

**Comment by struz** [comment]
Just did my own testing on this as well, after finding the issue independently. It seems like these credentials cannot be used for anything that the node role can do, so this isn't a problem.

If there is evidence to the contrary I will gladly reopen this issue.
