### ISSUE TITLE
How kube2iam works ?

### ISSUE THREAD

**Issue by kenwan12** [jtblin/kube2iam#23]
Does Kube2iam listen to docker events and hence detect the start of the  a new container and then construct the IAM role to assume using the base-role + role-name from the container's am.amazonaws.com/role value (K8s Annotations) ?

Are the results cached ?
If 2 containers being started at the same time, how does it handle then ?

Thanks

Ken

**Comment by jtblin** [comment]
kube2iam listens to kubernetes events not docker events. It retrieves the label from the pod using the kubernetes API. Therefore it doesn't matter if 2 containers are started at the same time.

Assumed role is cached for 15 minutes.
