### ISSUE TITLE
AWS metadata API change on AWS for c4/m4 instance

### ISSUE THREAD

**Issue by samuelb** [jtblin/kube2iam#237]
The kube2iam release 0.9.1 fixed an issue with c5/m5 instance, where the AWS metadata API have changed and kube2iam log is showing `Invalid role: does not match annotated role`. See #127 and https://github.com/mikkeloscar/kube2iam/commit/1f2da6c2c87ee2d0d368457f86bdd495914f26c9

Looks like the AWS API behaves now the same for m4 and possible other instances too. People (like we :sweat_smile:)  which are still running kube2iam < 0.9.1 need to update now.

**Comment by dggreenbaum** [comment]
This affected my c4 instances. Upgrading did the trick. TYVM.
