### ISSUE TITLE
What version of docker is needed to run kube2iam please ?

### ISSUE THREAD

**Issue by kenwan12** [jtblin/kube2iam#25]
I used a CoreOS k8s cluster running docker 1.10.3 to test using kube2iam with fstab/aws-cli
and somehow the aws-cli container could not have the specified role assumed.
 
Is it due to the docker version being 1.10.3 ?

There is no logging about it in the kube2iam log.
Would like to see if it is possible to turn on more verbal logging to trace the issue

Many thanks

Ken

**Comment by kenwan12** [comment]
It turned out that docker version 1.10.3 is OK but I need to use

--host-interface=cni0
 
to start kube2aim :-)

**Comment by jtblin** [comment]
Glad that your issue is fixed, FYI you can use the --verbose flag for more
verbose logs. Also --host-interface=cni0 is documented on the readme with
other various virtual networks.
