### ISSUE TITLE
add healthchecks

### ISSUE THREAD

**Issue by rickypai** [jtblin/kube2iam#26]
kube2iam should provide healthchecks such as `/healthz` and `/healthz/ping` so kubelet can ensure the proxies are running correctly.

some requirements:
- encapsulate it in a different path, like maybe `/kube2iam`, so it's explicit that `169.254.169.254/kubei2am` is specific to the proxy, and not affect any paths that might be exposed by the metadata service itself.

having this path also provides an easy way to check whether `169.254.169.254` goes to EC2 Metadata Service or kube2iam. If it goes to kube2iam, then `169.254.169.254/kube2iam/healthz/ping` should return 200. it's potentially useful to debug iptables rule to make sure the redirection goes to the proxy correctly, since bare EC2 Metadata Service doesn't have that endpoint.

`/healthz/ping` seems easy to implement with just returning a `200 ok`. `/healthz` might be more complicated depending on what we want to check. i might take a stab at `/healthz/ping`

**Comment by jtblin** [comment]
Great idea, feel free to give it a go. 

> /healthz/ping seems easy to implement with just returning a 200 ok. /healthz might be more complicated depending on what we want to check. 

Yep, not sure what we'd want to check here, connectivity to the cluster maybe.

**Comment by rickypai** [comment]
I think `/healthz` would probably check connectivity with `kube-apiserver` and `EC2 Metadata Proxy`. I'm going off for a two weeks, and I can take a stab then.

**Comment by jtblin** [comment]
@rickypai are you still planning to do that? Otherwise I'll probably implement the basic health check soon-ish.

**Comment by rickypai** [comment]
yeah, I haven't been able to do this. feel free to implement this

**Comment by jtblin** [comment]
Done, mounted at `/healthz`.
