### ISSUE TITLE
kube2iam for normal docker containers.

### ISSUE THREAD

**Issue by prudhvigodithi** [jtblin/kube2iam#269]
Hey, I'm using kube2iam with the process mentioned in the docs and works as described in the docs, so far so good, we are using weave as the host interface, but our process involves running docker containers inside the pod which uses host docker daemon, so by default, that docker container started inside the pod will now have host ec2 IAM role capabilities, can we use this kube2iam for individual docker containers using docker run --label iam.amazonaws.com/role: Test-Limited <conatiner>, so that this container that was started will also have that limited IAM role without having host ec2 IAM role?

**Comment by jtblin** [comment]
I don't think so.
