### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by kenwan12** [jtblin/kube2iam#27]
Hi,

   Want to build my own image and would like to confirm if I am to run the Alpine container on a CoreOS k8s cluster, shall I compile kube2iam on a Alpine VM or a CoreOS version is fine please ?

Thanks

Ken

**Comment by jtblin** [comment]
I build on Mac and have been running the image on a CoreOS cluster without issue. The host machine on which you compile should not matter. You can have a look at the Makefile and the Dockerfile should work for you.

**Comment by kenwan12** [comment]
Thanks, will take a look at the Makefile first.

**Comment by kenwan12** [comment]
👍 

Use  CGO_ENABLED=0 GOOS=linux GOARCH=x86_64 go build ...
and got the right kube2iam to run on the Alpine container

Thanks

Ken
