### ISSUE TITLE
Adopt the helm chart?

### ISSUE THREAD

**Issue by davidkarlsen** [jtblin/kube2iam#277]
Please see https://github.com/helm/charts/issues/21103
The helm stable repo is about to shut down.
Would you be interested in maintaining the chart here?
We have tooling like shown in https://github.com/helm/charts-repo-actions-demo to support a workflow for testing and releasing charts. Visibility on the [Helm Hub](https://hub.helm.sh/) is done through https://github.com/helm/hub
CC @scottrigby

**Comment by scottrigby** [comment]
Note that Nov 13, 2020 the `stable` repo will be unsupported.

**Comment by mariusv** [comment]
@davidkarlsen if nobody is interested I can pick this one up and maintain it as I'm using it on a daily basis on about 50 clusters CC @scottrigby

**Comment by scottrigby** [comment]
I just pinged @jtblin on Slack and by email in case this was missed. One note: if @jtblin agrees to host it under their github username just like the project is, the chart could be marked "official" in the CNCF Artifact Hub https://artifacthub.io/

**Comment by jtblin** [comment]
Yes I'm happy to host it, however I do not have much time to maintain it so I'd love to enlist @mariusv help for that.

**Comment by scottrigby** [comment]
@mariusv I would suggest following similar steps as I did for the prometheus-community charts: https://github.com/prometheus-community/helm-charts/issues/3

Then, as @davidkarlsen said in https://github.com/jtblin/kube2iam/issues/277#issue-675581486 you can emulate the GitHub Actions in the demo repo for CI/CD. If you'd like help with that please let me know 😄

**Comment by jtblin** [comment]
> Awesome, I'll do a PR with the chart and add it to the `chart` directory ? Or you prefer any other path @jtblin ?

@mariusv PR is great 👍

**Comment by benfrench1** [comment]
Hi @jtblin and @mariusv , hope you are well. 
I have a silly question....where is the proposed new location for the kube2iam helm chart? Can you post the link please, that would be much appreciated 😄.
Many thanks

**Comment by denniswebb** [comment]
@jtblin I'm open to doing the PR for the chart. Where were you planning on hosting the packaged chart? Just a GitHub pages site?

**Comment by dan-slinky-ckpd** [comment]
Any update on this? As per the deprecation timeline, the chart repos will likely be garbage collected and no longer available from Friday 13th November 2020 - happy to help contribute.

**Comment by mariusv** [comment]
@dan-slinky-ckpd [PR](#287 ) is here. We need @jtblin to create the Github pages to be able to host the chart

**Comment by mariusv** [comment]
@jtblin I can enable github pages on my fork if you want but I guess you'd rather do this under this repo

**Comment by zhimsel** [comment]
This should be reopened. The chart itself was migrated here, but there is no repo yet set up to host it.

**Comment by mariusv** [comment]
@zhimsel good catch. Added a new PR to fix the README issues #289

**Comment by mariusv** [comment]
@jtblin could you please enable Github Pages so I can push the chart in there? I can also enable it on my repo but would rather have it here

**Comment by mariusv** [comment]
@jtblin t[his is](https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kd) what needs to be done

**Comment by benfrench1** [comment]
Is there any update on this :)

**Comment by jtblin** [comment]
Ok, I've completed the configuration and triggered a release event. It seems to have created http://jtblin.github.io/kube2iam/index.yaml, is that all that's needed?

**Comment by chadlwilson** [comment]
Thanks a lot @jtblin - it seems to be working via `helm fetch kube2iam --repo http://jtblin.github.io/kube2iam` so I guess updating the `README` and such for a new version via #289 is all that is required here now.
