### ISSUE TITLE
Fix README for the chart

### ISSUE THREAD

**Issue by mariusv** [jtblin/kube2iam#288]
The chart README is still pointing to the stable deployment and also the chart repo is wrong

**Comment by matharoo** [comment]
Hi I tried the new updated repo to install the chart, but seems like the link is down. I am getting a 404 when trying to add the repo with :
`helm repo add kube2iam https://kube2iam.github.io/charts/`

```
Error: looks like "https://kube2iam.github.io/charts/" is not a valid chart repository or cannot be reached: failed to fetch https://kube2iam.github.io/charts/index.yaml : 404 Not Found
```

therefore cannot install the chart.

**Comment by walkafwalka** [comment]
@jtblin needs to setup a GitHub pages. Based on the current structure, it will eventually be `https://jtblin.github.io/charts/`.
