### ISSUE TITLE
Add iptables rule on startup

### ISSUE THREAD

**Issue by mgoodness** [jtblin/kube2iam#3]
Me again!

Would you be interested in a PR that enables kube2iam to add the necessary iptables rule?

**Comment by jtblin** [comment]
Yes that would be interesting. Maybe behind a flag e.g. --iptables so that
it is opt-in.

Would that work when kube2iam is run as a docker container with --net=host?

**Comment by mgoodness** [comment]
> Yes that would be interesting. Maybe behind a flag e.g. --iptables so that it is opt-in.

My thought/plan exactly.

> Would that work when kube2iam is run as a docker container with --net=host?

Yup. Also requires iptables installed in the image, and the pod must run with a privileged securityContext.

The code I have is appending the rule as expected, but traffic is not yet being routed to the kube2iam pod. Will submit the PR once I've figured that out.

**Comment by dedalusj** [comment]
Don't know if it is your problem as well but I was setting this up a couple of days ago and I found that the iptables rule needs to be changed from interface `docker0` to `cbr0`.

When kubernetes starts on a node it restarts docker pointing it to the `cbr0` interface as bridge. It puzzled me for a while. Hope it helps.

**Comment by mgoodness** [comment]
@dedalusj I suspect my issue is very similar, with Calico + flannel making things complicated.

**Comment by mgoodness** [comment]
I ended up disabling Calico, as it uses iptables to perform DNAT of its own. Need to research more to see if & how it can play nicely with kube2iam. In the meantime, I have things working with flannel using the `docker0` interface.
