### ISSUE TITLE
error in logs

### ISSUE THREAD

**Issue by razic** [jtblin/kube2iam#35]
This is showing up in the logs every second or so:

```
E1130 18:15:04.738072       1 reflector.go:214] github.com/jtblin/kube2iam/cmd/k8s.go:39: Failed to list *api.Pod: Get https://172.16.0.1:443/api/v1/pods?resourceVersion=0: x509: cannot validate certificate for 172.16.0.1 because it doesn't contain any IP SANs
```

why is this hitting the pod api at the private ip when i have explicitly specified the `--api-server` option?

**Comment by jtblin** [comment]
As discussed on Slack, `KUBERNETES_SERVICE_HOST` was set in your containers to this IP which was causing this issue. Closing.
