### ISSUE TITLE
Add helm chart with ARM support

### ISSUE THREAD

**Issue by flipsed** [jtblin/kube2iam#356]
Based on the changelog, multi-arch support was added in v0.11.0.

Although the docker image for 2.6.0 is supposed to support ARM arch (https://hub.docker.com/r/jtblin/kube2iam/tagshttps://hub.docker.com/r/jtblin/kube2iam/tags), the pod from the helm chart for 2.6.0 is failing with a CrashLookBackOff and this error message:
```bash
standard_init_linux.go:228: exec user process caused: exec format error
```

We should increase the helm chart app version and bump the chart version.

Note: the latest helm charts 3.0.0 and 3.1.0 are not in the registry since the release is failing (see #354)

```bash
helm search repo kube2iam  --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
kube2iam/kube2iam       2.6.0           0.10.9          Provide IAM credentials to pods based on annota...
kube2iam/kube2iam       2.5.2           0.10.9          Provide IAM credentials to pods based on annota...
```

**Comment by RITESHBRID** [comment]
when this chart will be available?
