### ISSUE TITLE
Valid iptable Interface format with wildcards(+) are treated as wrong

### ISSUE THREAD

**Issue by alexouzounis** [jtblin/kube2iam#37]
Since https://github.com/jtblin/kube2iam/commit/d55bfe9e275279d7d5244da42134b402b7025354 we get:

```
2016-12-15T14:10:18.858624928Z time="2016-12-15T14:10:18Z" level=fatal msg="route ip+net: no such network interface" 
```

This is probably because we use `cali+` as the interface and the check implemented in the above commit is marking it as incorrect even though its valid.

**Comment by alexouzounis** [comment]
reverted to `0.2.2` and everything works as expected

**Comment by alexouzounis** [comment]
iptables support;
```
If the interface name ends in a "+", then any interface which begins with this name will match. If this option is omitted, any interface name will match.
```
which the above commit does not take into account.

Let me know if you need any more info

**Comment by johnt337** [comment]
I had commented to your notes on the PR. Moving my notes here:

So here is my example with using the interface as cbr0
![image](https://cloud.githubusercontent.com/assets/1334469/21240764/ae1a9dbe-c2da-11e6-8017-54224d173d14.png)

I traced that back to https://golang.org/src/net/interface.go line 155:

```
138 // InterfaceByName returns the interface specified by name.
139	func InterfaceByName(name string) (*Interface, error) {
140		if name == "" {
141			return nil, &OpError{Op: "route", Net: "ip+net", Source: nil, Addr: nil, Err: errInvalidInterfaceName}
142		}
143		ift, err := interfaceTable(0)
144		if err != nil {
145			return nil, &OpError{Op: "route", Net: "ip+net", Source: nil, Addr: nil, Err: err}
146		}
147		if len(ift) != 0 {
148			zoneCache.update(ift)
149		}
150		for _, ifi := range ift {
151			if name == ifi.Name {
152				return &ifi, nil
153			}
154		}
155		return nil, &OpError{Op: "route", Net: "ip+net", Source: nil, Addr: nil, Err: errNoSuchInterface}
156	}
```

It appears that sometimes the interfaces are not ready (or available)

My cluster is running: `Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}`

@alexouzounis are you running kubernetes 1.4.6 by chance?

**Comment by johnt337** [comment]
So upon further investigation, I can confirm that some of my hosts are not coming up with the cbr0 interface. I can add a patch to ignore the "+", but in my case its behaving correctly and catching the fact that the interface is not configured.

**Comment by alexouzounis** [comment]
Thanks for looking at it @johnt337 ! 

Noticed it in clusters running `1.4.4` `1.4.6` and `1.5.1` - downgrading kube2iam to `0.2.2` consistently makes the error disappear

**Comment by alexouzounis** [comment]
All clusters use CoreOs + flannel + calico and all interfaces start with `cali` hence why in kube2iam the interface name specified is `cali+`

**Comment by ls-yann-david** [comment]
I just hit the same issue, reverting to 0.2.2 worked as well!
