### ISSUE TITLE
Support for other resource types

### ISSUE THREAD

**Issue by pingles** [jtblin/kube2iam#40]
I (stupidly) was trying to figure out why it wasn't working but then realised I was testing Job resources (part of the beta batch api). Although they ultimately create pods the annotations were associated on the Job (and not the Pod).

I'll probably take another look soon as I'd like to start using Job resources for testing a CD system.

Thanks so much for the project!

**Comment by jtblin** [comment]
I think but haven't tested that you should be able to add annotations on the pod template in the job definition, see #49 which seems related.
