### ISSUE TITLE
BadRequest: Container kube2iam is not available

### ISSUE THREAD

**Issue by mirague** [jtblin/kube2iam#50]
This showed up in the logs of my **Master Node**:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"kube2iam\" in pod \"kube2iam-xc54t\" is not available","reason":"BadRequest","code":400}
```

It doesn't error on my two slave nodes.

How do I go about debugging this?

**Comment by mirague** [comment]
False alarm. There wasn't enough CPU available on the master.

**Comment by jtblin** [comment]
Thanks for following up.
