### ISSUE TITLE
0.3.3 prepends base arn to security-credentials

### ISSUE THREAD

**Issue by cnelson** [jtblin/kube2iam#54]
0.3.3 seems to have changed the behavior of this app and it now prepends the base-role-arn to the security-credentials responses which seems to prevent containers from accessing the credentials for their role.

Is 0.3.3 known to not be backwards compatible (if so, how should we adjust our configuration?) or is this a bug?

**With 0.3.3**
```
# run inside a container via kubectl exec
curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/

arn:aws-us-gov:iam::ACCOUNT:role/bosh-passed/k8s-logger

curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/arn:aws-us-gov:iam::ACCOUNT:role/bosh-passed/k8s-logger

Invalid role arn:aws-us-gov:iam::ACCOUNT:role/bosh-passed/k8s-logger
```

**On 0.3.1 this worked as expected:**
```
# run inside a container via kubectl exec

curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/

k8s-logger

curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/k8s-logger

{"Code":"Success","LastUpdated":"2017-03-07T16:23:04Z","Type":"AWS-HMAC","AccessKeyId":"...","SecretAccessKey":"...","Expiration":"2017-03-07T16:53:04Z"}
```

kube2iam is started with the following options: `--base-role-arn=arn:aws-us-gov:iam::ACCOUNT:role/bosh-passed/ --default-role=k8s-node  --host-ip=192.0.2.229 --iptables=true` and the examples above are from a container that's been annotated to have the `k8s-logger` role rather than the default role

**Comment by struz** [comment]
This is a regression - sorry about that. It is fixed in https://github.com/jtblin/kube2iam/pull/55
