### ISSUE TITLE
Allow policy to control which namespaces are able to assume which roles

### ISSUE THREAD

**Issue by pingles** [jtblin/kube2iam#57]
We're in the process of experimenting with running a cluster where many different teams would be able to deploy their different apps onto the same cluster. We'd like to be able to control which processes are able to assume which roles- so a role which allows access to a particular KMS resource would only be available to pods running in the `kube-system` namespace, for example.

Is anyone else working on this (or interested in something like it)?

**Comment by SleepyBrett** [comment]
This just got merged the other day.

**Comment by struz** [comment]
This is in release 0.4.0

**Comment by pingles** [comment]
Awesome, sorry for the dupe- I was looking through other issues and
couldn't see anything obvious. Will try out the updated release asap.
Thanks for all your work on this- a super useful project for us!!
