### ISSUE TITLE
Building against kubernetes v1.5.3 client version is broken

### ISSUE THREAD

**Issue by jescarri** [jtblin/kube2iam#60]
```$ make build
gofmt -w=true -s $(find . -type f -name '*.go' -not -path "./vendor/*")
goimports -w=true -d $(find . -type f -name '*.go' -not -path "./vendor/*")
go build -o build/bin/darwin/kube2iam -ldflags "-s -X ""github.com/jtblin"/kube2iam"/version.Version=$(git describe --abbrev=0 --tags) -X ""github.com/jtblin"/kube2iam"/version.GitCommit=$(git rev-parse --short HEAD) -X ""github.com/jtblin"/kube2iam"/version.BuildDate=$(date +%Y-%m-%d-%H:%M)" github.com/jtblin/kube2iam
# github.com/jtblin/kube2iam/cmd
cmd/k8s.go:20: undefined: "github.com/jtblin/kube2iam/vendor/k8s.io/kubernetes/pkg/client/unversioned".Client
make: *** [build] Error 2```

After running 
```glide get github.com/aws/aws-sdk-go/blob/master/aws/ec2metadata#^v1.0.8```

doing a diff to glide.lock I found that it was never updated to v1.5.3

````
-- name: k8s.io/client-go
-  version: 6631b2769fbf8fd8ff6b2074d64774b010c7d37a
-  subpackages:
-  - 1.4/pkg/api
-  - 1.4/pkg/api/endpoints
-  - 1.4/pkg/api/errors
-  - 1.4/pkg/api/meta
-  - 1.4/pkg/api/meta/metatypes
-  - 1.4/pkg/api/pod
-  - 1.4/pkg/api/resource
-  - 1.4/pkg/api/service
-  - 1.4/pkg/api/unversioned
-  - 1.4/pkg/api/unversioned/validation
-  - 1.4/pkg/api/util
-  - 1.4/pkg/api/v1
-  - 1.4/pkg/api/validation
-  - 1.4/pkg/apimachinery
-  - 1.4/pkg/apimachinery/registered
-  - 1.4/pkg/apis/autoscaling
-  - 1.4/pkg/apis/batch
-  - 1.4/pkg/apis/extensions
-  - 1.4/pkg/auth/user
-  - 1.4/pkg/capabilities
-  - 1.4/pkg/conversion
-  - 1.4/pkg/conversion/queryparams
-  - 1.4/pkg/fields
-  - 1.4/pkg/labels
-  - 1.4/pkg/runtime
-  - 1.4/pkg/runtime/serializer
-  - 1.4/pkg/runtime/serializer/json
-  - 1.4/pkg/runtime/serializer/protobuf
-  - 1.4/pkg/runtime/serializer/recognizer
-  - 1.4/pkg/runtime/serializer/streaming
-  - 1.4/pkg/runtime/serializer/versioning
-  - 1.4/pkg/security/apparmor
-  - 1.4/pkg/selection
-  - 1.4/pkg/third_party/forked/golang/reflect
-  - 1.4/pkg/types
-  - 1.4/pkg/util
````

**Comment by jtblin** [comment]
Client version has been downgraded to 1.4.3 as part of https://github.com/jtblin/kube2iam/releases/tag/0.5.0

**Comment by jtblin** [comment]
The kubernetes client code has moved to https://github.com/kubernetes/client-go/ so I updated the code to use it instead of the main kubernetes project directly as before: 68ab0a8
