### ISSUE TITLE
Please provide release notes

### ISSUE THREAD

**Issue by hjacobs** [jtblin/kube2iam#64]
There are some new releases since 0.3.0 (which we are using in production, see https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/kube2iam/daemonset.yaml), but they are lacking release notes: https://github.com/jtblin/kube2iam/releases

It would be nice to have concise release notes instead of reading the whole code diff :smirk:

**Comment by jtblin** [comment]
Done, thanks for the reminder.

**Comment by hjacobs** [comment]
Thanks!
