### ISSUE TITLE
Use pod namespace and name in logs to identify pods

### ISSUE THREAD

**Issue by ankon** [jtblin/kube2iam#68]
kube2iam currently identifies the pods using their "remote address", but that means when scanning through these logs one needs to manually translate IPs into "which pod is that?" This is especially problematic in highly volatile environments, where IPs get recycled over time. 

Operationally I do need to be able to review a kube2iam log and check that the pods I do assign roles get the these roles, and pods that should get the default roles do.

It would be really helpful if mate could log the pod namespace _and_ name for each log message related to a specific pod.

**Comment by jtblin** [comment]
I've added pod and namespace where possible. There are a few places where we don't have the pod name but I intend to tackle that when I implement the new `NewIndexerInformer` instead of the store. I'll keep this issue open until it's done.
