### ISSUE TITLE
Provide a way to specify the AWS region

### ISSUE THREAD

**Issue by astratto** [jtblin/kube2iam#72]
At the moment, when creating the AWS Session object no region can be specified (i.e., https://github.com/jtblin/kube2iam/blob/master/cmd/iam.go#L79).

The effect of this is that calls to STS default to https://sts.amazonaws.com and according to [AWS](http://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html) that URL maps to US East but could as well change.

In some corporate environments, such calls are restricted per region and AWS provides local endpoint that can be [used](http://docs.aws.amazon.com/general/latest/gr/rande.html#sts_region).

The AWS APIs provide a way to specify the region when creating the Session object: https://docs.aws.amazon.com/sdk-for-go/api/aws/session

**Comment by jtblin** [comment]
Would it possible to just set an environment variable for that like `AWS_REGION`?

**Comment by jtblin** [comment]
Confirmed in the [environment variables section](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Environment_Variables) of the SDK. I think I'd prefer that an environment variable is used for this use case to avoid adding complexity.
