### ISSUE TITLE
IAM roles not applied to init containers

### ISSUE THREAD

**Issue by ahawkins** [jtblin/kube2iam#74]
The title says it all. Pods in the deployment correctly assume the declared IAM role. However this does not work for init containers. This is problem for us because our init containers needs to bootstrap AWS resources (governed by the IAM policy). Luckily we can get around this for now, but may not be able to in the future. Are init containers supposed to be working or is this a feature request?

**Comment by jescarri** [comment]
@ahawkins have you tried to also annotate the init containers?
I can confirm kube2iam works with init containers, they need to be annotated as any other pod.

**Comment by ahawkins** [comment]
Turns out this was our bad. Please ignore :bow:
