### ISSUE TITLE
Restrict role assignment to single container

### ISSUE THREAD

**Issue by schlomo** [jtblin/kube2iam#82]
Consider a [multi conainter setup](https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/) with an application and a maintenance container. The maintenance container is used to copy backups to S3.

How could I restrict access to the injected AWS credentials to only the maintenance container so that the main container with the (internet exposed) application won't have access to them?

Maybe also interesting: How do give different roles to different containers on the same pod.

**Comment by emmanuel** [comment]
The Pod is the unit of identity for a workload. I think that trying to provide access to creds only for one of several container in a pod is going to increase complexity significantly. Also, I think that approach would be generally working against the conceptual model of Kubernetes.

**Comment by jtblin** [comment]
I agree with @emmanuel, the IP address is the same for all containers AFAIK so I don't think we'd be able to distinguish between containers. I'd recommend using multiple pods in this case, or looking at other solutions that implement similar functionalities at the docker level.
