### ISSUE TITLE
--auto-discover-default-role broken in 0.6.2+

### ISSUE THREAD

**Issue by c-knowles** [jtblin/kube2iam#83]
[This commit](https://github.com/jtblin/kube2iam/commit/0efea8c28c88d8fca66b60ad7ea6caadc2010dec#diff-d40ff635e38cff8f5959411f50e5a8a6) changed the metadata lookup for default IAM role but to a value that does not exist:

```
-	iamRole, err := metadata.GetMetadata("iam/security-credentials/")
+	iamRole, err := metadata.GetMetadata("Client/security-Credentials/")
```

**Comment by jtblin** [comment]
Sorry about that, it looks like my IDE renamed strings when I did the refactoring. Released 0.6.4 with the fix.
