### ISSUE TITLE
Regex for `--base-role-arn` is not permissive enough

### ISSUE THREAD

**Issue by cnelson** [jtblin/kube2iam#84]
The regex added to fix #71 (https://github.com/jtblin/kube2iam/blob/master/cmd/main.go#L40) is not permissive enough.  It fails on arns that are valid and worked in previous versions of kube2iam.

For example we were using this arn with `0.6.2` without issue: 
`arn:aws-us-gov:iam::916510818310:role/bosh-passed/`

**Comment by jtblin** [comment]
Sorry about that, I was sure I was going to miss something with this. I changed the regex and added tests to verify that this kind of arn works. Released 0.6.4 with the fix.
