### ISSUE TITLE
Log level for health check requests

### ISSUE THREAD

**Issue by johanneswuerbach** [jtblin/kube2iam#85]
The log level for health check requests seems to be `info` causing every health check request to be logged by default and making it hard to see the actual output of kube2iam.

Would it be possible to decrease the log level to `debug` or similar for health check requests?

Example log:
```
2017-06-16T12:42:33.811901607Z time="2017-06-16T12:42:33Z" level=info msg="Handling request" req.method=GET req.path="/healthz" req.remote=172.18.116.255 res.duration=963249 res.status=200 
```

**Comment by jtblin** [comment]
I chose to remove the logging for the health endpoint as we don't actually have the information about the log level at this point in the code actually.
