### ISSUE TITLE
Handling dynamic role names

### ISSUE THREAD

**Issue by lstoll** [jtblin/kube2iam#88]
When roles are created via CloudFormation or other dynamic tooling in an environment that can support multiple clusters per AWS account, the role names are usually either not predictable or vary between Kubernetes Clusters. This makes manifest management more complex, because the annotations are hard embedded and can't be substituted from ConfigMaps or the like. This has resulted in having to template out these fields externally, which is somewhat of a hassle.

It would be nice to have a way to use consistent arn references in manifests, and rely on kube2iam to map these to the kubernetes cluster specific values. I've had a few thoughts on how to do this.

**1. Global Prefix/Suffix**:  Allow specifying a prefix or suffix for role names as a flag to kube2iam. arn's are specified in manifests without this, and then kube2iam will apply this to the name. Pros: do not need to know all the name mappings up front. Cons: doesn't allow for mixed usage - where some roles are cluster specific, and some are not

**2. Explicit mappings as CLI flag**: Allow explicit mappings to be specific as a series of CLI flags like `--arn-alias=simple-name,arn:aws::iam:1234567890::role/stack-aasdkhkjhakjhasd-role-name`. Manifests refer to the simple name, kube2iam switches it out internall. Pros: simple, explicit, can be defined per role. Cons: need to know ahead of time the specific mappings in use, need to update the daemonset on change.

I prefer 2. It's more explicit and likely less surprising over time. These could also potentially be used to solve the issue in #59 as well. I briefly considered the idea of using a regex filter here as well, but that would make for a complex implementation and potentially surprising behaviour (e.g what happens if two roles match the regex?)

I'm happy to work up an implementation for this, I just wanted to float the idea for preliminary discussion/approval before diving in.

**Comment by idubrov** [comment]
Is it possible to have an option 3, where role name is retrieved from the environment variable (which in turn will be could from the config map)?

**Comment by antoniobeyah** [comment]
Our use case: We restrict teams to namespaces and only want to allow namespaces to assume roles that match their namespaces.  We are mapping namespaces to paths within IAM.  We don't really care what the actual role is as long as it is within the namespace of the team.  Role names are generated dynamically, so we don't know them ahead of time.

Our goal is to be able to annotate the namespace with an allowed roles that match the path as we define in IAM.

For example:
**Namespace:** `namespace1`
**Allowed Assumption:** `arn:aws:iam::123456789012:role/namespace1/*`
**Example IAM Roles:**
- `arn:aws:iam::123456789012:role/namespace1/myrole-sjoiejois`
- `arn:aws:iam::123456789012:role/namespace1/newrole-sjeois`

**Comment by matt-deboer** [comment]
@antoniobeyah PR #104 allows restriction based on path globbing

**Comment by jtblin** [comment]
Closing as it is now possible to use namespace path globbing

**Comment by willejs** [comment]
@lstoll does this actually fix your issue? I am experiencing a similar problem... I want to supply a prefix that gets added to the role, the suggested fix does not support this.
