### ISSUE TITLE
Cross account assume role not working

### ISSUE THREAD

**Issue by r0fls** [jtblin/kube2iam#91]
Is this supported, or is possibly a missing feature? Here is a more detailed summary of my situation:

I have one role assigned to a kubernetes deployment, which has assume role capabilities for 3 other roles (two of which are on different accounts from the role assigned to the k8s deployment). It works to assume the role that is also on the kubernetes deployment, but not the other two. There I get:

```
AccessDenied: User: arn:aws:sts::*****:assumed-role/<ROLE-NAME>/6fa16a-<ROLE-NAME>
is not authorized to perform: sts:AssumeRole on resource: 
arn:aws:iam::*****:role/<OTHER-ROLE-NAME> 
```

**Comment by r0fls** [comment]
whoops, i think this was just iam misconfiguration

**Comment by moos3** [comment]
what was your miss configuration @r0fls ?
